server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: produit
          uri: lb://PRODUIT
          predicates:
            - Path=/produits/**
        - id: client
          uri: lb://CLIENT
          predicates:
            - Path=/clients/**
        - id: facture
          uri: lb://FACTURE
          predicates:
           - Path=/factures/**
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/